app_name: "jenkins"
app_home: "/var/lib/{{ app_name }}"
app_port: 8080
app_version: "2.479.1"
app_url: "http://127.0.0.1:{{ app_port }}/{{ app_name }}"

systemd_path: "/etc/systemd/system/{{ app_name }}.service.d"

corretto_home_path: "/usr/lib/jvm/corretto/"
corretto_version: "17.0.13.11.1/"

nginx_cofig_path: "/etc/nginx/sites-available/{{ app_name }}.conf"

apt_key: "https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key"
apt_key_location: "/usr/share/keyrings/jenkins-keyring.asc"
apt_repo: "deb [signed-by={{ apt_key_location }}] https://pkg.jenkins.io/debian-stable binary/"
user: admin

app_secret_path: "{{ app_home }}/secrets/initialAdminPassword"

plugins:
  - "authentication-tokens"
  - "prism-api"
  - "mercurial"
  - "cloud-stats"
  - "apache-httpcomponents-client-5-api"
  - "branch-api"
  - "workflow-job"
  - "matrix-project"
  - "handy-uri-templates-2-api"
  - "workflow-basic-steps"
  - "pipeline-model-definition"
  - "okhttp-api"
  - "checks-api"
  - "echarts-api"
  - "kubernetes-credentials"
  - "kubernetes-client-api"
  - "metrics"
  - "javadoc"
  - "jsch"
  - "pipeline-groovy-lib"
  - "commons-compress-api"
  - "pipeline-groovy-lib"
  - "cloudbees-folder"
  - "git"
  - "docker-plugin"
  - "docker-commons"
  - "docker-java-api"
  - "docker-workflow"
  - "github-api"
  - "github-branch-source"
  - "github"
  - "pipeline-github-lib"
  - "credentials-binding"
  - "maven-plugin"
  - "junit"
  - "ssh-agent"
  - "parameterized-trigger"
  - "job-dsl"
  - "timestamper"
  - "build-timeout"
  - "workflow-multibranch"
  - "active-choices"
  - "pipeline-utility-steps"
  - "workflow-aggregator"
  - "cloudbees-bitbucket-branch-source"
  - "bitbucket"
  - "bitbucket-push-and-pull-request"
  - "jacoco"
  - "checkstyle"
  - "pmd"
  - "findbugs"
  - "sonar"
  - "artifact-deployer"
  - "deploy-to-container"
  - "maven-integration-plugin"
  - "kubernetes"
  - "helm"
  - "kubernetes-cd"
  - "kubernetes-cli"
