---
- name: Install Jenkins
  hosts: localhost
  become: true

  vars:
    key_location: /usr/share/keyrings/jenkins-keyring.asc
    tmp_key_location: /tmp/jenkins-keyring.asc

  tasks:
    - name: Update package cache
      ansible.builtin.apt:
        update_cache: true

    - name: Install Java
      ansible.builtin.apt:
        # Debian 12 Doesn't have support to jdk 11 anymore, using 17 instead.
        name: openjdk-17-jdk
        state: present

    - name: Install Jenkins Keys
      block:
        - name: Download Jenkins ASC Key
          ansible.builtin.get_url:
            url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
            dest: "{{ tmp_key_location }}"
            mode: "0440"

        - name: Install GPG Key
          register: apt_key
          changed_when: apt_key.rc != 0
          ansible.builtin.shell: |
            cat {{ tmp_key_location }} | gpg --batch --yes --dearmor --quiet -o {{ key_location }}
          args:
            executable: /bin/bash

        - name: Update file permission
          ansible.builtin.file:
            path: "{{ key_location }}"
            mode: "0444"

        - name: Remove tmp file
          ansible.builtin.file:
            path: "{{ tmp_key_location }}"
            state: absent

        - name: Install APT repository
          ansible.builtin.apt_repository:
            repo: "deb [signed-by={{ key_location }}] https://pkg.jenkins.io/debian-stable binary/"
            state: present
            filename: jenkins.list

    - name: Install Jenkins
      ansible.builtin.apt:
        name: jenkins
        state: present

    - name: Start Jenkins service
      ansible.builtin.service:
        name: jenkins
        state: started
        enabled: true
