- name: Install each Jenkins plugin
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: "{{ jenkins_user }}"
    url_password: "{{ jenkins_password }}"
    url: "{{ jenkins_url }}"
  loop: "{{ plugins }}"
  register: plugin_installation_result

- name: Show plugin installation result
  debug:
    var: plugin_installation_result

