- name: Create service user
  block:
    - name: Create group
      ansible.builtin.group:
        name: "java"
        state: present

    - name: Update User Permissions
      ansible.builtin.file:
        path: "{{ corretto_home_path }}"
        group: "java"
        owner: "java"
        state: "directory"
        mode: "0555"
        recurse: true

    - name: Create user
      ansible.builtin.user:
        name: "java"
        comment: "Service account for running java"
        shell: /usr/sbin/nologin
        home: "{{ corretto_home_path }}"
        create_home: true
        system: true
