- name: Wait for Jenkins to be ready
  ansible.builtin.wait_for:
    port: 8080
    timeout: 60

- name: Retrieve initial admin password
  ansible.builtin.slurp:
    src: /opt/jenkins/secrets/initialAdminPassword
  register: initial_admin_password_file

- name: Decode initial admin password
  ansible.builtin.set_fact:
    admin_password_file: "{{ initial_admin_password_file.content | b64decode }}"

- debug:
    var: admin_password_file.content

- name: Debug login response
  ansible.builtin.debug:
    var: "{{ initial_admin_password_file.content | b64decode }}"

- name: Install each Jenkins plugin
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: "admin"
    url_password: "{{ initial_admin_password_file }}"
    url: "{{ jenkins_url }}"
  loop: "{{ plugins }}"
  register: plugin_installation_result

- name: Show plugin installation result
  debug:
    var: plugin_installation_result
