- name: Configure Jenkins with JCasC
  ansible.builtin.template:
    src: "roles/{{ app_name }}/templates/jenkins.yaml"
    dest: "{{ app_home }}/jenkins.yaml"
    group: "{{ app_name }}"
    owner: "{{ app_name }}"
    mode: "0640"

- name: Jenkins Post Install
  block:
    - name: Add the user to the docker group
      ansible.builtin.user:
        name: "{{ app_name }}"
        groups: docker
        append: true

    - name: Enable Service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started
        enabled: true

- name: Retrieve initial admin password
  ansible.builtin.slurp:
    src: "{{ app_home }}/secrets/initialAdminPassword"
  register: initial_admin_password_file

- name: Decode initial admin password
  ansible.builtin.set_fact:
    admin_password_file: "{{ initial_admin_password_file.content | b64decode | regex_replace('\\n', '') }}"

- name: Show decoded admin password
  debug:
    var: admin_password_file

- name: Install each Jenkins plugin
  community.general.jenkins_plugin:
    name: "{{ item }}"
    url_username: "admin"
    url_password: "{{ admin_password_file }}"
    url: "{{ jenkins_url }}"
  loop: "{{ plugins }}"
