- name: Download and Extract
  block:
    - name: Download Corretto tar file
      ansible.builtin.get_url:
        url: "{{ corretto_archive_url }}"
        dest: "{{ corretto_tmp_file }}"
        mode: "0555"

    - name: Create temporary directory
      ansible.builtin.file:
        path: "{{ corretto_tmp_path }}"
        state: directory
        owner: "java"
        group: "java"
        mode: "0555"

    - name: Extract Corretto archive to temporary path
      ansible.builtin.unarchive:
        src: "{{ corretto_tmp_file }}"
        dest: "{{ corretto_tmp_path }}"
        remote_src: true

- name: Update the path and installs java
  block:
    - name: Install Java To Correct Folder
      ansible.builtin.copy:
        src: "{{ corretto_tmp_path }}/amazon-corretto-{{ corretto_version }}-linux-x64/"
        dest: "{{ corretto_home_path }}/{{ corretto_version }}"
        remote_src: true
        mode: "0555"
        owner: "java"
        group: "java"

    - name: Creates Symlink
      ansible.builtin.file:
        src: "{{ corretto_home_path }}/{{ corretto_version }}/bin/java"
        dest: "/usr/bin/java-jenkins"
        mode: "0777"
        owner: "java"
        group: "java"
        state: link

- name: Clean environment
  block:
    - name: Remove temporary file
      ansible.builtin.file:
        path: "{{ corretto_tmp_file }}"
        state: absent

    - name: Remove temporary path
      ansible.builtin.file:
        path: "{{ corretto_tmp_path }}"
        state: absent
