- name: Install Jenkins Keys
  block:
    - name: Download Jenkins ASC Key
      ansible.builtin.get_url:
        url: "{{ jenkins_key }}"
        dest: "{{ jenkins_key_location }}"
        mode: "0640"
        group: "root"
        owner: "root"

    - name: Install APT repository
      ansible.builtin.apt_repository:
        repo: "{{ jenkins_repo }}"
        state: present
        filename: jenkins.list

- name: Install Jenkins
  ansible.builtin.apt:
    name: "jenkins={{ jenkins_version }}"
    state: present

- name: Create SystemD overwrite Config Folder
  ansible.builtin.file:
    state: directory
    owner: "{{ app_name }}"
    group: "{{ app_name }}"
    mode: "0640"
    path: "/etc/systemd/system/jenkins.service.d"


- name: Generate SystemD Config
  ansible.builtin.template:
    src: "roles/{{ app_name }}/templates/override.conf.j2"
    dest: "/etc/systemd/system/jenkins.service.d/override.conf"
    group: "{{ app_name }}"
    owner: "{{ app_name }}"
    mode: "0755"

- name: Jenkins Post Install
  block:
    - name: Add the user to the docker group
      ansible.builtin.user:
        name: "{{ app_name }}"
        groups: docker
        append: true

    - name: Enable Service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started
        enabled: true

    - name: Wait for 60 seconds
      ansible.builtin.pause:
        seconds: 60
      when: true

    - name: Stop Service
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: stopped
