- name: Create CASC path
  ansible.builtin.file:
    path: "{{ app_home }}/casc_configs"
    state: directory
    group: "{{ app_name }}"
    owner: "{{ app_name }}"
    mode: "0640"

- name: Configure Jenkins with JCasC
  ansible.builtin.template:
    src: "roles/{{ app_name }}/templates/jenkins.yaml"
    dest: "{{ app_home }}/casc_configs/jenkins.yaml"
    group: "{{ app_name }}"
    owner: "{{ app_name }}"
    mode: "0640"

- name: Jenkins Post Install
  block:
    - name: Add the user to the docker group
      ansible.builtin.user:
        name: "{{ app_name }}"
        groups: docker
        append: true

    - name: Enable Service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started
        enabled: true

- name: Install each Jenkins plugin
  community.general.jenkins_plugin:
    name: "{{ item }}"
    # url_username: "admin"
    # url_password: "{{ admin_password_file }}"
    url: "{{ jenkins_url }}"
  loop: "{{ plugins }}"
