- name: Wait File
  block:
    - name: Wait for file to appear if it doesn't exist
      ansible.builtin.wait_for:
        path: "{{ app_secret_path }}"
        state: present
        timeout: 180
    - name: Wait for file to exist
      ansible.builtin.stat:
        path: "{{ app_secret_path }}"
      register: file_stat

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ file_stat.stat.exists }}"

- name: Install Jenkins Plugins
  block:
    - name: Retrieve initial admin password
      ansible.builtin.slurp:
        src: "{{ app_secret_path }}"
      register: initial_admin_password_file

    - name: Decode initial admin password
      ansible.builtin.set_fact:
        admin_password_file: "{{ initial_admin_password_file.content | b64decode | regex_replace('\\n', '') }}"

    - name: Show decoded admin password
      ansible.builtin.debug:
        var: admin_password_file

    - name: Install each Jenkins plugin
      community.general.jenkins_plugin:
        name: "{{ item }}"
        url_username: "{{ user }}"
        url_password: "{{ admin_password_file }}"
        url: "{{ app_url }}"
      loop: "{{ plugins }}"
