- name: Install Jenkins
  ansible.builtin.include_tasks: install_jenkins.yaml

- name: Install Java as Dependency
  ansible.builtin.include_tasks: install_java.yaml

# - name: Install Jenkins Plugins
#   ansible.builtin.include_tasks: install_jenkins_plugins.yaml
