#- name: Install Java SA
#  ansible.builtin.include_tasks: create_service_account.yaml
#
#- name: Install Java as Dependency
#  ansible.builtin.include_tasks: install_java.yaml
#
#- name: Install Jenkins
#  ansible.builtin.include_tasks: install_jenkins.yaml
#
#- name: Install Jenkins Plugins
#  ansible.builtin.include_tasks: install_jenkins_plugins.yaml

#- name: Install NGINX Reverse Proxy
#  ansible.builtin.include_tasks: install_nginx.yaml

- name: Create Jenkins Job
  ansible.builtin.include_tasks: install_jobs.yaml
