- name: Service Configuration
  block:
    - name: Enable Service
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Start Service
      ansible.builtin.service:
        name: "{{ app_name }}"
        state: started
        enabled: true

    - name: Configure Permissions
      ansible.builtin.file:
        path: "{{ app_home }}"
        state: directory
        recurse: true
        owner: "{{ app_name }}"
        group: "{{ app_name }}"
        mode: "0750"
